language: php
php:
  - '7.2'

before_script:
  - printf "\n" | pecl install yaml
  - composer self-update
  - composer install --dev --no-interaction
  - pip install coverage
script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit --colors --coverage-text --coverage-clover=coverage.xml
after_success:  
  - bash <(curl -s https://codecov.io/bash)
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
