language: php
php:
  - '7.2'

before_script:
  - composer self-update
  - composer install --dev --no-interaction
script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit --colors --coverage-text --coverage-clover build/logs/clover.xml
  - php vendor/bin/phpcs --colors
after_success:  
  - travis_retry php vendor/bin/php-coveralls