# ┌────┐┌────┐┌────┐┌────┐┌────┐
# │ ┌──┘│ ┌┐ ││ ┌┐ ││ ┌──┘│ ┌──┘
# │ └┐  │ ││ ││ └┘ ││ │   │ └──┐
# │ ┌┘  │ ││ ││ ┌┐ ││ │   └──┐ │
# │ │   │ └┘ ││ ││ ││ └──┐┌──┘ │
# └─┘   └────┘└─┘└─┘└────┘└────┘
# Copyright Foacs
# contributor(s): Alexis DINQUER
#
# (2019-05-08)
#
# contact@foacs.me
#
# This software is a computer program whose purpose is to handle data persistence in PHP
#
# This software is governed by the CeCILL-C license under french law and
# abiding by the rules of distribution of free software. You can use,
# modify and/ or redistribute the software under the terms of the CeCILL-C
# license as circulated by CEA, CNRS and INRIA at the follow URL
# "http://www.cecill.info".
#
# As a counterpart to the access to the source code and rights to copy,
# modify and redistribute granted by the license, users are provided only
# with a limited warranty and the software's authors, the holder of the
# economic rights, and the successive licensors have only limited
# liability.
#
# In this respect, the user's attention is drawn to the risk associated
# with loading, using, modifying and/ or developing or reproducing the
# software by the user in light of its specific status of free software,
# that may mean that it is complicated to manipulate, and that also
# therefore means that it is reserved for developers and experienced
# professionals having in-depth computer knowledge. Users are therefore
# encouraged to load and test the software's suitability as regards their
# requirements in conditions enabling the security of their systems and/or
# data to be ensure and, more generally, to use and operate it in the
# same conditions as regards security.
#
# The fact that you are presently reading this means that you have had
# knowledge of the CeCILL-C license and that you accept its terms.
language: php
php:
  - '7.2'

before_script:
  - printf "\n" | pecl install yaml
  - composer self-update
  - composer install --dev --no-interaction
  - pip install coverage --user
script:
  - php vendor/bin/phpunit --colors --coverage-clover coverage.xml
  - php vendor/bin/phpcs --colors
after_success:  
  - bash <(curl -s https://codecov.io/bash)
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
